### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by Bra1nsen** [waggle-sensor/plugin-cmv-fftpc#2]
Hello I hope you are all fine :)
I have a SkyCam on my roof and I would like to try out your code! Unfortunately, I'm still quite a beginner. How exactly do I get your code to run? I am using windows.
The SkyCam runs on a Raspberry Pi.

Many thanks for your help.
Paul

**Comment by Bra1nsen** [comment]
So I mean I can start app.py in the console, but I can't find any result / output

**Comment by jswantek** [comment]
Hi Paul!

This might not be helpful for your specific use-case but...

This plugin/application is one of many applications of the SAGE (https://sagecontinuum.org/) project.  It's link in our "app store" can be found here: https://portal.sagecontinuum.org/apps/app/bhupendraraut/cloud-motion.  This application was specifically designed to operate within the SAGE software cyber-infrastructure.  If you would like to learn more about how the cyber-infrastructure works, how to develop and run applications on the infrastructure's remote nodes, or how to access the data please head on over to our docs: https://docs.sagecontinuum.org/

Let me know if you have questions!
Joe

**Comment by RBhupi** [comment]
Hi Paul, 
The above code captures real-time images and uploads the data in the cloud. It will need changes to read your data and output CMV in a text file. If you can run the app.py without errors, that means you managed to get the camera input. You may then want to print(u_mean) and print(v_mean) and see if the output makes sense.
Also, check the Sage portal for other cool apps using sky camera https://portal.sagecontinuum.org/apps/explore 

Thanks for reaching out. 

Bhupendra

**Comment by Bra1nsen** [comment]
Thanks for your feedback! I'm really happy about that.

I have registered on your site. i am interested in cloud motion and short-term forecasts for solar systems using sky imager. where exactly are the results saved? Are there any tutorials out there? Your applications look very promising, I'm really excited.

**Comment by jswantek** [comment]
Hi!

Our program is in it's early stages so there isn't a lot of data from the cloud motion and other applications quite yet.  But starting in January (of 2022) you should start to see data populating in our database.  The instructions for accessing the data can be found here: https://data.sagecontinuum.org/
